config/routes.rb
Rails.application.routes.draw do
  get 'scrapings/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'accueil', to: 'static_pages#home', as: 'home'
  get 'agence', to: 'static_pages#agency', as: 'agency'
  get 'services', to: 'static_pages#services'
  get 'mentions-legales', to: 'static_pages#legal_notice', as: 'legal_notice'
  get 'politique-de-confidentialite', to: 'static_pages#privacy_policy', as: 'privacy_policy'
  get 'site-sur-mesure', to: 'static_pages#custom_website', as: 'custom_website'
  get 'site-pre-construit', to: 'static_pages#prebuilt_website', as: 'prebuilt_website'
  get 'marketing-digital', to: 'static_pages#digital_marketing', as: 'digital_marketing'
  get 'referencement-seo', to: 'static_pages#seo', as: 'seo'
  get 'bornes-tactile', to: 'static_pages#touch_terminal', as: 'touch_terminal'

  get 'contact', to: 'contacts#new', as: 'new_contact'
  post 'contact', to: 'contacts#create', as: 'create_contact'
  get 'contacts/:id', to: 'contacts#show', as: 'contact'

  namespace :admin do
    resources :contacts, only: [:index]
  end

  resources :scrapings, only: [:index]
  resources :mailing_logs, only: [:index, :create]

  post 'admin/contacts/send_prospect_emails', to: 'admin/contacts#send_prospect_emails', as: 'send_prospect_emails'
  get 'admin/contacts/send_prospect_emails', to: 'admin/contacts#send_prospect_emails', as: 'prospect_emails_sent'
  # get 'admin/contacts/prospect_emails_sent', to: 'admin/contacts#prospect_emails_sent', as: 'prospect_emails_sent'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_one :mailing_log
  # after_create :send_email

  # validates :first_name, presence: { message: "Vous n'avez saisi aucun prénom." }
  # validates :last_name, presence: { message: "Vous n'avez saisi aucun nom." }
  # validates :email, presence: { message: "Vous n'avez saisi aucun e-mail." }, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "L'e-mail saisi est incorrect." }
  # validates :subject, presence: { message: "Vous n'avez saisi aucun un objet pour votre message." }
  # validates :message, presence: { message: "Vous n'avez saisi aucun message." }
end

app/models/mailing_log.rb
class MailingLog < ApplicationRecord
  belongs_to :contact
end

app/models/scraping.rb
class Scraping < ApplicationRecord
end

app/models/user_contact.rb
class UserContact < Contact
  after_create :send_email

  attr_accessor :subject, :message

  validates :first_name, presence: { message: "Vous n'avez saisi aucun prénom." }
  validates :last_name, presence: { message: "Vous n'avez saisi aucun nom." }
  validates :email, presence: { message: "Vous n'avez saisi aucun e-mail." }
  validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "L'e-mail saisi est incorrect." }, if: -> { email.present? }
  validates :subject, presence: { message: "Vous n'avez saisi aucun sujet pour votre message." }
  validates :message, presence: { message: "Vous n'avez saisi aucun message." }

  def send_email
    response = AdminMailer.user_contact_email(self).deliver_now
    puts "TEST MAIL REPONSE :"
    p response
    puts "END OF TEST"
  end
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def send_prospect_emails
    puts "TEST PROPECT PARAMS :" + params.to_s
    params["youpi"] = "blabla"
    @youpi = "blabla"
    # redirect_to prospect_emails_sent_path(ids: params[:contact_ids])
    render "prospect_emails_sent"
  end

  def prospect_emails_sent
    puts "test1 --> " + @youpi.to_s
    puts "TEST PROPECT PARAMS BIS :" + params.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = UserContact.new
  end

  def create
    # @contact = UserContact.new(
    @contact = UserContact.new(permitted_params)
    @contact.source = "input_user"

    if @contact.save # essaie de sauvegarder dans la bdd

      # si ça marche, il redirige vers la page show
      redirect_to contact_path(@contact.id)
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      render "new"
    end
  end

  private
    # Using a private method to encapsulate the permissible parameters
    # is just a good pattern since you'll be able to reuse the same
    # permit list between create and update. Also, you can specialize
    # this method with per-user checking of permissible attributes.
    def permitted_params
      params.require(:user_contact).permit(:first_name, :last_name, :company, :email, :subject, :message) # "subject" et "message" sont des attributs non persistants
    end
  end

app/controllers/mailing_logs_controller.rb
class MailingLogsController < ApplicationController

  def index
    @logs = MailingLog.all
  end

  def create
    puts "TEST PROPECT PARAMS :" + params[:contact_ids].to_s


    params[:contact_ids].each { |id|
      contact = Contact.find(id)
      log = MailingLog.find_by(contact: contact)
      if log != nil
        log.update(messages_count: log.messages_count + 1)
      else
        log = MailingLog.create(contact: contact, status:"none", messages_count:0)
      end

      AdminMailer.prospect_email(contact).deliver_now
      log.update(status: "sent")
    }

    redirect_to mailing_logs_path
  end

end

app/controllers/scrapings_controller.rb
class ScrapingsController < ApplicationController
  def index
    @scrapings = Scraping.all
    @youpidd = "test"
  end

  def refresh
    #@user = @user + 1

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def agency
  end

  def services
  end

  def legal_notice
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/mailing_logs_helper.rb
module MailingLogsHelper
end

app/helpers/scrapings_helper.rb
module ScrapingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue-grey lighten-5">

<div class="footer-bar">
<!-- Grid row-->
<div class="text-footer-bar">
<h6 id="title-footer">Restez connecté avec nous sur les réseaux sociaux !</h6>
</div>
<!-- Grid column -->

<!-- Grid column -->
<div class="logo-footer-content">
<!-- Facebook -->
<a id=logo-bar-footer class="fb-ic fa-2x" href="https://www.facebook.com/mercadev/">
<i class="fab fa-facebook-f white-text"></i>
</a>
</div>
</div>

<!-- Footer Links -->
<div class="container text-center text-md-left mt-5">

<!-- Grid row -->
<div class="row mt-3 dark-grey-text">

<!-- Grid column -->
<div class="col-md-3 col-lg-4 col-xl-3 mb-4">

<!-- Content -->
<h6 class="text-uppercase font-weight-bold">Mercadev</h6>
<hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
<p>La proximité est une priorité pour nous. <br>
Nous sommes proches de nos clients et de nos partenaires et serions ravis d'échanger avec vous.</p>
</div>

<!-- About Grid column -->
<div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

<!-- Links -->
<h6 class="text-uppercase font-weight-bold">À propos</h6>
<hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
<p>
<a class="dark-grey-text" href="<%= legal_notice_path %>">Mentions légales</a>
</p>
<p>
<a class="dark-grey-text" href="<%= privacy_policy_path %>">Politique de confidentialité</a>
</p>
</div>

<!-- Infos Grid column -->
<div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

<!-- Links -->
<h6 class="text-uppercase font-weight-bold">Contact</h6>
<hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
<p>
<i class="fas fa-home mr-3"></i>Bordeaux, 33000, France</p>
<p>
<i class="fas fa-envelope mr-3"></i><a href="mailto:contact@mercadev.fr">contact@mercadev.fr</a></p>

<div id="infos-contact"><p id="contact-job">Responsable marketing</p>
<hr-job class="teal accent-3 d-inline-block" style="width: 110px;"></div>
<p><i class="fas fa-phone mr-3"></i>06 04 15 01 79</p>

<div id="infos-contact"><p id="contact-job">Responsable technique</p>
<hr-job class="teal accent-3 d-inline-block" style="width: 110px;"></div>
<p><i class="fas fa-phone mr-3"></i>06 70 33 85 50</p>
</div>
</div>

<!-- Copyright -->
<div class="footer-copyright text-center text-black-50 py-3">© 2019 Copyright:
<a class="dark-grey-text" href="<%= root_path %>">by Mercadev</a>
</div>
<!-- Copyright -->

</footer>
<!-- Footer -->

app/views/layouts/_header.html.erb
<!-- Navigation -->
<header>
	<nav class="navbar navbar-expand-lg navbar-light navbar-fixed-top fixed-top">
		<div class="nav-container">
			<a class="navbar-brand" href="<%= root_path %>"><img src="<%= image_path('company_logo.png') %>" alt="Logo mercadev" id="company_logo"></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active">
						<a class="nav-link" href="<%= home_path %>">Accueil
							<span class="sr-only">(current)</span>
						</a>
					</li>
					<li class="nav-item active">
						<a class="nav-link" href="<%= agency_path %>">L'agence</a>
					</li>

					      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sites web
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= prebuilt_website_path %>">Site web pré-construit</a>
          <a class="dropdown-item" href="<%= custom_website_path %>">Site web sur mesure</a>
      </div>
  </li>

  <li class="nav-item dropdown active">
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Marketing
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= digital_marketing_path %>">Marketing digital</a>
          <a class="dropdown-item" href="<%= seo_path %>">Référencement Google</a>
        </div>
      </li>
      <li class="nav-item active">
						<a class="nav-link" href="<%= touch_terminal_path %>">Bornes tactiles</a>
					</li>
					<li class="nav-item active">
						<a class="nav-link" href="<%= new_contact_path %>">Contact</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
</header>

app/views/static_pages/_interest.html.erb
<div class="underline-service"></div>

	<div class="row" id="what-row">
		<div class="text-team-box">
			<div class="text-digital">
				<div> <center> <h3 id="title-what">Vous êtes intéressé ?</h3></center><div>
					<center>Assurer sa présence sur internet nécessite un véritable travail de fond.<br>
						Que vous soyez un particulier ou un professionnel, la création de votre site internet, l’amélioration de votre positionnement passe par le bon choix de votre agence web.<br>
					Nous sommes des professionnels capable de répondre à tous vos besoins numériques.</p></center></div>
					<center> <a class="btn btn-primary" href="<%= new_contact_path %>">Nous contacter</a></center>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/_website_comparative_chart.html.erb
<div class="underline-service"></div>
		<div id="what-row" class="row mb-0">
		<div class="text-team-box">
			<div class="text-digital my-0">
				<div> <center><h3 id="title-what" class="my-4 py-0">Comparez nos deux solutions</h3></center><div>
				</div>
			</div>
		</div>
	</div>
</div>

<section class="pricing mt-0 pb-0">
  <div class="container-table">
    <div class="row justify-content-center mx-auto">

      <div class="col-lg-4">
        <div class="card mb-5 mb-lg-0">
          <div class="card-body bg-light">
            <h5 class="card-title text-muted text-uppercase text-center">Site pré-construit</h5>
            <hr>
            <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Création site web</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Maintenance du site web</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Intégration de votre identité visuelle</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Fonctionnalités basiques</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Initialisation référencement Google</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Nom de domaine (www.votresociété.fr)</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Adresse mail 10 max. (exemple@votresociété.fr)</li>
              <li class="text-muted"><span class="fa-li"><i class="fas fa-times"></i></span>Design sur mesure</li>
              <li class="text-muted"><span class="fa-li"><i class="fas fa-times"></i></span>Fonctionnalités complexes</li>
            </ul>
             <a href="<%= prebuilt_website_path %>" class="btn btn-block btn-primary text-uppercase">En savoir plus</a>
          </div>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="card mb-5 mb-lg-0">
          <div class="card-body bg-light">
            <h5 class="card-title text-muted text-uppercase text-center">Site sur mesure</h5>
            <hr>
                        <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Création site web</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Maintenance du site web</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Intégration de votre identité visuelle</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Fonctionnalités basiques</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Initialisation référencement Google</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Nom de domaine (www.votresociété.fr)</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Adresse mail 10 max. (exemple@votresociété.fr)</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Design sur mesure</li>
              <li><span class="fa-li"><i class="fas fa-check"></i></span>Fonctionnalités complexes</li>
            </ul>
            <a href="<%= custom_website_path %>" class="btn btn-block btn-primary text-uppercase">En savoir plus</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/agency.html.erb
<!-- Carousel -->

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
<!-- <ol class="carousel-indicators">
<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
</ol> -->
<div class="carousel-inner" role="listbox">
<!-- Slide One - Set the background image for this slide in the line below -->
<div id="item-1" class="carousel-item active" style="background-image: url('https://images.pexels.com/photos/380769/pexels-photo-380769.jpeg?w=1920')" alt="Photo agence web mercadev">
<div class="carousel-caption">
<h3 class="display-4">L'agence</h3>
<p class="lead">Création de site internet, référencement et marketing digital en Aquitaine</p>
</div>
</div>
</div>
</div>

<!-- text content -->
<div id="intro-text">
Située à Bordeaux, en Aquitaine, Mercadev est une agence web et de marketing digital.<br>
Axés sur les TPE, PME, artisans, commerçants, professions libérales, nous mettons en œuvre des solutions de marketing digital adaptées à votre activité et à vos besoins : site internet, charte graphique, logo, stratégie digitale...<br>
Nous travaillons sur le webdesign, le référencement, le marketing digital, et la communication via les réseaux sociaux.
<!-- 		          <a class="btn btn-primary" href="<%= new_contact_path %>">Nous contacter</a> -->
</div>

<!-- Page card team content -->
<div class="row" id="team-row">
<div class="text-team-box">
<div class="text-team">
<h3 id="agency-title">Notre équipe</h3>
<div id=hr-agency style="width: 130px;"></div>
<p>Avec plusieurs années d'expérience dans le design, le développement informatique, la gestion de projet et le marketing digital, notre équipe possède l'ensemble des compétences pour booster votre visibilité sur internet.<br>
Proches de nos clients, nous mettons tout en oeuvre afin de satisfaire vos demandes dans les meilleurs délais.</p>
</div>
</div>
</div>

<!-- Digital Card -->
<div class="row" id="digital-row">
<div id="logo-digital-card"><i class="fas fa-desktop fa-4x"></i></div>
<div class="text-team-box">
<div class="text-digital">
<div id="title-card"> <center> <h3 id="digital-title">Maîtrise du digital</h3></center><div>
<p class="card-text">
Dernières innovations en matière de création de site internet, stratégie digitale, design, visibilité sur le web grâce au référencement (SEO), laissez notre équipe prendre en charge votre image dans un monde numérique en constante transformation.</p>
</div> </div> </div>
</div>
</div>

<div class="row" id="digital-row">
<div id="logo-digital-card"><i class="fas fa-pencil-alt fa-4x"></i></div>
<div class="text-team-box">
<div class="text-digital">
<div id="title-card"> <center> <h3 id="digital-title">Créativité</h3></center><div>
<p class="card-text">
Face à vos concurrents, il est essentiel de dégager une image forte et valorisante de votre entreprise.<br>
Notre équipe créative vous aide à vous démarquer avec une identité qui marque vos clients.</p>
</div> </div> </div>
</div>
</div>

<div class="row" id="digital-row">
<div id="logo-digital-card"><i class="fas fa-users fa-4x"></i></div>
<div class="text-team-box">
<div class="text-digital">
<div id="title-card"> <center> <h3 id="digital-title">à l'écoute</h3></center><div>
<p class="card-text">
Commençons par mieux connaître votre métier ainsi que vos besoins.<br>
Prenons en compte les spécificités de votre entreprise et de vos clients.<br>
Identifions votre clientèle, ses attentes, mais aussi ses craintes.</p>
</div> </div> </div>
</div>
</div>

<div class="row" id="what-row">
<div class="text-team-box">
<div class="text-digital">
<div> <center> <h3 id="title-what">Que pouvons-nous faire pour vous ?</h3></center><div>
<p>
Quelle que soit votre activité, il est aujourd'hui primordial d'avoir une identité visuelle unique afin de séduire vos prospects dès le premier coup d’œil. « La première impression est souvent la bonne ». Vous devez impacter les esprits pour qu’un client potentiel choisisse votre offre plutôt que celle du voisin.</p>
<p>Notre métier chez Mercadev consiste à vous créer une image unique, reconnaissable et percutante. Votre vitrine doit refléter votre professionnalisme et inspirer confiance.</p>
<p>Mercadev participe à tout le processus créatif et met à votre service son équipe spécialiste de la communication pour vous conseiller. Grâce à nos compétences dans le référencement naturel sur Internet, nous incluons les éléments clés de votre communication sur le web.</p>
<p>Mercadev met l’accent sur l’écoute du client, car c'est le plus à même de fixer la feuille de route. Nous travaillons avec vous afin de cerner tous les points qui serviront à bâtir votre identité sur Internet.</p>
<p>L’équipe de graphistes et de webdesigners de Mercadev travaille ensuite sur une offre sur mesure et valorisante pour votre entreprise. Une fois votre identité visuelle établie, nous la déclinons sur tous les supports dont vous allez avoir besoin : Internet, flyers, cartes de visite, kakémonos, affichage grand format… Notre équipe reste toujours à votre disposition pour travailler avec vous sur votre stratégie digitale, pour améliorer votre référencement naturel, développer votre audience et multiplier vos clients potentiels.</p>
<p>Parce que nous connaissons les contraintes et les impératifs des entreprises, nous donnons une importance capitale à être parfaitement scrupuleux quant au respect du cahier des charges, du budget et des délais.
</p>
</div> </div> </div>
</div>
</div>

app/views/static_pages/home.html.erb
<!-- Carousel -->

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
<ol class="carousel-indicators">
<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
</ol>
<div class="carousel-inner" role="listbox">
<!-- Slide One - Set the background image for this slide in the line below -->
<div id="item-1" class="carousel-item active" style="background-image: url('https://images.pexels.com/photos/1483938/pexels-photo-1483938.jpeg?w=1920')">
<div class="carousel-caption">
<h1 id="mercadev" class="display-4">MERCADEV</h1>
<p class="lead">Développez votre marché</p>
</div>
</div>
<!-- Slide Two - Set the background image for this slide in the line below -->
<div id="item-2" class="carousel-item" style="background-image: url('https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?w=1920')">
<div class="carousel-caption">
<h1 class="display-4">Votre site web sur mesure</h1>
<p class="lead">Mercadev crée votre site selon vos critères et votre identité visuelle</p>
</div>
</div>
<!-- Slide Three - Set the background image for this slide in the line below -->
<div id="item-3" class="carousel-item" style="background-image: url('https://images.pexels.com/photos/533446/pexels-photo-533446.jpeg?w=1920')">
<div class="carousel-caption">
<h1 class="display-4">Réseaux sociaux</h1>
<p class="lead">Afin d'étendre votre clientèle, nous pouvons développer votre visibilité sur les réseaux sociaux</p>
</div>
</div>
</div>
<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
<span class="carousel-control-prev-icon" aria-hidden="true"></span>
<span class="sr-only">Précédent</span>
</a>
<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
<span class="carousel-control-next-icon" aria-hidden="true"></span>
<span class="sr-only">Suivant</span>
</a>
</div>

<!-- card desk content -->
<div class="card-deck-content">

<div class="card-deck">

<a href="<%= custom_website_path %>" class="card" id="a-card">
<img class="card-img-top"> <i class="far fa-object-group fa-3x" id=logo-card></i>
<div class="card-body">
<h5 class="card-title">Création site web</h5>
<p class="card-text">Mercadev crée votre site selon vos critères et votre identité visuelle.<br>
Grâce à une conception "Responsive", votre site s'adaptera à tous les supports : ordinateur, tablette, smartphone...</p>
</div>
</a>

<a href="<%= digital_marketing_path %>" class="card" id="a-card">
<img class="card-img-top"> <i class="fas fa-bullhorn fa-3x" id=logo-card> </i>
<div class="card-body">
<h5 class="card-title">Marketing digital</h5>
<p class="card-text">Nous vous accompagnons pour vous permettre de capter l’attention de vos prospects et de les transformer en clients fidèles, grâce à la mise en place d’une stratégie web complète ou des actions plus ponctuelles.</p>
</div>
</a>

<a href="<%= seo_path %>" class="card" id="a-card">
<img class="card-img-top"><i class="fab fa-google fa-3x" id=logo-card></i>
<div class="card-body">
<h5 class="card-title">Référencement SEO</h5>
<p class="card-text">Nous appliquons un plan SEO à partir de mots-clés et de liens afin de faire apparaître votre boutique en tête de liste sur Google.</p>
</div>
</a>
</div>

<div class="card-deck" >

<a href="<%= digital_marketing_path %>" class="card" id="a-card">
<img class="card-img-top"> <i class="far fa-comments fa-3x" id=logo-card></i>
<div class="card-body">
<h5 class="card-title">Réseaux sociaux</h5>
<p class="card-text">Afin d'étendre votre clientèle, nous pouvons développer votre visibilité sur les réseaux sociaux.<br>
Nous proposons de créer et animer votre page Facebook et/ou votre compte Instagram.</p>
</div>
</a>

<a href="<%= custom_website_path %>" class="card" id="a-card">
<img class="card-img-top"> <i class="fas fa-server fa-3x" id=logo-card> </i>
<div class="card-body">
<h5 class="card-title">Hébergement et maintenance</h5>
<p class="card-text">Votre site sera hébergé sur un serveur sécurisé. Nous assurons une maintenance afin que votre site soit le plus performant possible.</p>
</div>
</a>

<a href="<%= touch_terminal_path %>" class="card" id="a-card">
<img class="card-img-top"> <i class="fas fa-tablet-alt fa-3x" id=logo-card> </i>
<div class="card-body">
<h5 class="card-title">Bornes tactiles</h5>
<p class="card-text">Que ce soit pour l’intérieur ou l’extérieur, les bornes tactiles sont conçues pour créer une expérience unique et mieux gérer les flux de consommateurs lors des heures de grande affluence.</p>
</div>
</a>
</div>
</div>

<!-- Page card content -->
<div class="row" id="agency-row">
<div class="img-agency"> 
<img class="img-fluid" src="https://images.pexels.com/photos/380769/pexels-photo-380769.jpeg?w=700" alt="Photo agence web mercadev">
</div>
<div class="text-agency-box">
<div class="text-agency">
<h3 id="agency-title">Notre agence</h3>
<div id=hr-agency style="width: 120px;"></div>
<p>Notre agence web et marketing est située à Bordeaux en Aquitaine.<br>
Elle regroupe une équipe dynamique et passionnée qui vous accompagne dans vos projets de communication digitale.<br> 
Pour des marques, des produits ou des enseignes, nous proposons des prestations de conseil et de stratégie en communication / publicité, et nous assurons leur réalisation technique.</p>
<a class="btn btn-primary" id="btn-agency-contact" href="<%= new_contact_path %>">Nous contacter</a>
</div>
</div>
</div>